logging:
  level:
    org:
      springframework: INFO
spring:
  datasource:
    CSV:
      url: jdbc:h2:./CSV
      username: sa
      password: password
      driverClassName: org.h2.Driver
      generate-unique-name: false
    JSON:
      url: jdbc:sqlite:./JSON.db
      username: sa
      password: sa
      driverClassName: org.sqlite.JDBC
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  sql:
    init:
      mode: always

